# jeux:
#    resource: "@JeuxBundle/Controller/"
#    type:     annotation
#    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

main_page:
    path:      /
    defaults:  { _controller: JeuxBundle:Default:index }

hello_page:
    path:      /{name}
    defaults:  { _controller: JeuxBundle:Default:hello }
birthday_page:
    path: /{monthInLetters}/{day}
    defaults:  { _controller: JeuxBundle:Default:birthday}
