<?php

namespace JeuxBundle\Repository;

/**
 * WordListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordListRepository extends \Doctrine\ORM\EntityRepository
{
}
